Keysend bLIP
lightning/blips pull request #5
Opened 2021-12-09 17:11 UTC by valentinewallace

Migrated from https://github.com/lightning/bolts/pull/892

2021-12-10 01:19 UTC, lightning-developer requested changes
Thank you for the write up and the nice bLIP. I guess it is not very controversial as it is already being implemented almost everywhere. 

Despite the comments in the text I was mainly wondering if we should specify the payment amount and what happens if the amount in the last onionion payload does not match what was being forwarded. Theoretically an intermediate node could try to send a lower amount and hope it is a keysend payment and see if the recipient settles. so I guess the recipient MUST also check that the value of the incoming HTLC matches the field in the onion and SHOULD otherwise fail the payment even though they MAY accept it.

2021-12-10 01:19 UTC, lightning-developer commented on blip-0003.md
> +* MUST reject the keysend if the preimage does not match the payment hash
also  with `PERM|15 incorrect_or_unknown_payment_details` ?

2021-12-10 01:19 UTC, lightning-developer commented on blip-0003.md
> +* MUST reject the keysend if a `payment_data` field is present in the onion
is present or is NOT present?

2021-12-10 01:19 UTC, lightning-developer commented on blip-0003.md
> +Note that because of the lack of a payment secret, basic MPP payments are not
Why not? several key sends could signal that they are to be understood as an MPP for a final amount? Not sure though if we want this additional complexity In particular as the recieving node could settle the HTLCs before the final amount arrived resulting in various problems

2021-12-10 01:19 UTC, lightning-developer commented on blip-0003.md
> +Additionally, as of authoring this bLIP, keysend is used in multiple lightning
I think this sentence is not necessary for the bLIP thus I suggest to delete it.

2021-12-10 01:19 UTC, lightning-developer commented on blip-0003.md
> +  its security properties. A future direction for keysend could be deciding that
How would that work? I am not sure if the MPP rational needs to be explained. Here we could just keep MPP completely out of the bLIP and create a new one if we think MPP is necessary for keysend at some point in the future.

2021-12-10 08:02 UTC, t-bast reviewed
Thanks for putting this together!
I had never realized that MPP was disallowed with keysend, and really can't understand why, if you can enlighten me that would be great (eclair does allow MPP + Keysend).

2021-12-10 17:58 UTC, valentinewallace commented on blip-0003.md
> +* MUST NOT set a `payment_data` field in the onion routing packet's TLV payload
Ah I see, I don't mind removing this part and officially supporting MPP keysend. 

This was before the Libera switch so I could be misremembering, but I talked to @cdecker on IRC about MPP support in keysend and his thinking was that that a payer-supplied payment secret doesn't make sense (since it no longer serves to "authenticate" the sender iiuc). Would appreciate if cdecker could weigh in here?

2021-12-13 08:19 UTC, t-bast commented on blip-0003.md
> +* MUST NOT set a `payment_data` field in the onion routing packet's TLV payload
I don't think it matters at all. It's true that the `payment_secret` is redundant, as the preimage can act as the secret here, but as a recipient you really want to avoid revealing that preimage before you've received everything that the sender wanted you to receive, so you need to have a `total_amount` field in the onion (which the `payment_data` field provides).

As long as the receiver didn't reveal the preimage too early, intermediate nodes cannot cheat, as they don't know the preimage, and the receiver knows this is a keysend so it shouldn't accept HTLCs that don't contain the preimage in the onion payload.

2021-12-16 04:36 UTC, TheBlueMatt commented on blip-0003.md
> +* MUST NOT set a `payment_data` field in the onion routing packet's TLV payload
Its totally *possible* to support it, but IIUC lnd never did, and thus c-lightning, to match lnd's behavior, did not either. I could see an argument that without proof-of-payment for some given value a receiver may prefer to partial-claim an HTLC instead of failing it due to MPP timeout, but I'm not really sure it matters for the intended tipping use-case. It could conceivably complicate downstream UX, though, as you now have to *actually* handle partial-claim (instead of just treating it as ":shrug: full value claimed, cause we got proof-of-payment").

2021-12-16 22:07 UTC, valentinewallace commented on blip-0003.md
> +  the HTLC payment preimage
> MUST NOT reuse a previously used a preimage
MUST NOT reuse a preimage that was retrieved from paying a previous invoice.

Hmm, so from the onion bolt:

```
 the final node:
    if the payment hash has already been paid:
        MAY treat the payment hash as unknown.
        MAY succeed in accepting the HTLC.
```
Not certain on this, but it seems like it tends to be up to the final node how they want to treat duplicate payment hashes. So I lean towards leaving those rules out of this bLIP.

> MUST set the [sha256:payment_hash] field in the update_add_htlc to match SHA256 hash of the TLV value

Added this

2021-12-16 22:07 UTC, valentinewallace commented on blip-0003.md
> +* SHOULD only send payments to nodes advertising feature bit 55
reworded

2021-12-16 22:10 UTC, valentinewallace commented on blip-0002.md
> +| 5482373484 | `keysend_preimage`          | [bLIP 3](https://github.com/lightning/blips/blob/master/blip-0003.md) |
> Small nit: I'm wondering whether we should put these numbers in hex instead of decimal, it feels closer to how we actually use them

Huh, interally in LDK (and lnd I think) it's represent in decimal (so kinda nice greppability for the number with decimal). Could you elaborate on the "closer to how we actually use them" bit?

2021-12-16 22:18 UTC, valentinewallace commented on blip-0003.md
> +Note that because of the lack of a payment secret, basic MPP payments are not
>  the recieving node could settle the HTLCs before the final amount arrived resulting in various problems

This is already possible with `basic_mpp` payments 😛 

Gonna hold off on addressing some of these mpp comments until [this convo](https://github.com/lightning/blips/pull/5#discussion_r766451691) is more resolved

2021-12-16 22:24 UTC, valentinewallace commented on blip-0003.md
> +  time discrepancies due to a hash collision with X.
forget why I included this, I think it's somewhat specific to LDK so removed

2021-12-17 07:23 UTC, t-bast commented on blip-0002.md
> +| 5482373484 | `keysend_preimage`          | [bLIP 3](https://github.com/lightning/blips/blob/master/blip-0003.md) |
It's just that I've become used to reading encoded lightning messages in hex :nerd_face: but that's probably just me :laughing:

2021-12-17 07:29 UTC, t-bast commented on blip-0003.md
> +* MUST NOT set a `payment_data` field in the onion routing packet's TLV payload
I indeed don't think it matters for the tipping use-case...
Eclair has always allowed MPP with keysend, so I don't know if we should have these requirements about `payment_data`, maybe it's best to just not say anything about it?
That shows that it would have been great to specify this, now we have non-compatible implementations on the network (even though we never got users complaining about failures here, are we sure lnd and c-lightning actively reject keysend payments that contain a `payment_data` field?).

2021-12-17 09:01 UTC, cdecker commented on blip-0003.md
> +* MUST NOT set a `payment_data` field in the onion routing packet's TLV payload
Hm, I see how the payment_sata includes the total amount to be sent (why didn't we separate them...). I think that alone should be sufficient to keep it for MPP keysend support.

2021-12-21 19:44 UTC, valentinewallace commented on blip-0003.md
> +* MUST NOT set a `payment_data` field in the onion routing packet's TLV payload
Sounds good, removed the parts of the bLIP that specify MPP isn't supported

2021-12-22 07:39 UTC, t-bast approved these changes
LGTM, thanks @valentinewallace!

2021-12-22 07:41 UTC, merged

2022-01-11 03:55 UTC, Roasbeef commented
> I had never realized that MPP was disallowed with keysend, and really can't understand why, if you can enlighten me that would be great (eclair does allow MPP + Keysend).

A bit late on this, but it wasn't part of `keysend` as it was created _before_ we started to specify MPP as we know it today, namely the semantics around the `payment_addr/secret` field. Also given the pre-image is included directly in the payload, the receiver can pull at anytime, which means you can run into the same issues re partial fulfilment. AMP improves on this, as the payment can only be pulled once all the shards arrive. 

Also FWIW, most usage of keysend today on the network like the podcast annotation stuff usually uses pretty small amounts, so payment splitting isn't usually necessary in practice.

2022-02-04 09:19 UTC, joostjager commented on blip-0002.md
> +| 5482373484 | `keysend_preimage`          | [bLIP 3](./blip-0003.md)       |
Is this the right location for this table row? I think it should be part of the `payment_onion_payload` section.

>the `update_add_htlc` message's onion payload

What is this exactly? The `update_add_htlc` message can be extended with custom tlv fields, but that isn't the onion payload.

2022-02-04 09:21 UTC, t-bast commented on blip-0002.md
> +| 5482373484 | `keysend_preimage`          | [bLIP 3](./blip-0003.md)       |
Good catch, that does need to be fixed!

2022-02-04 17:40 UTC, valentinewallace commented on blip-0002.md
> +| 5482373484 | `keysend_preimage`          | [bLIP 3](./blip-0003.md)       |
Thanks @joostjager, corrected in #15

2026-10-19 16:32 UTC, stonersdash26 approved these changes